version: '{branch}-{build}'

clone_depth: 5

platform:
  - x64

configuration:
  - Release

environment:
  COMBINATION: win-%COMPILER%-%PLATFORM%-%CONFIGURATION%
  ARTIFACTS_ZIP_NAME: ShaderConductor-%COMBINATION%-artifacts.zip
  BUILD_DIR: ninja-%COMBINATION%
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      COMPILER: vc140
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      COMPILER: vc141

install:
  - choco install ninja

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - python BuildAll.py ninja %COMPILER% %PLATFORM% %CONFIGURATION%

test_script:
  - Build\%BUILD_DIR%\Bin\ShaderConductorTest.exe

after_test:
  - cd Build\%BUILD_DIR%
  - echo %APPVEYOR_REPO_COMMIT% > GIT-COMMIT.txt
  - xcopy "%APPVEYOR_BUILD_FOLDER%\Include\ShaderConductor" Include\ShaderConductor /s /i /y
  - 7z a %ARTIFACTS_ZIP_NAME% Include Lib\ShaderConductor.lib Bin\ShaderConductor.dll Bin\ShaderConductorCmd.exe Bin\dxcompiler.dll GIT-COMMIT.txt

artifacts:
  - path: Build\%BUILD_DIR%\%ARTIFACTS_ZIP_NAME%
